name: Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Append -dev to version on develop branch
        if: github.ref == 'refs/heads/develop'
        run: sed -i 's/version=.*/&-dev/' gradle.properties

      - name: Make Gradle Wrapper Executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Fabric Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Creeper-Confetti-Fabric
          path: fabric/build/libs/creeperconfetti-*.jar
          if-no-files-found: error

      - name: Upload NeoForge Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Creeper-Confetti-NeoForge
          path: neoforge/build/libs/creeperconfetti-*.jar
          if-no-files-found: error
